# Generated by Django 4.0.5 on 2022-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orders_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='pimage',
            field=models.ImageField(default='', upload_to='restaurant/images'),
        ),
    ]
