# Generated by Django 4.0.5 on 2022-08-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderBy',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_allorders',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_contact1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_contact2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_firstname',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_track',
            field=models.CharField(default='onprocess', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
