# Generated by Django 4.0.5 on 2022-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_orders_order_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_lastname',
            field=models.CharField(default='karki', max_length=12),
        ),
    ]
