# Generated by Django 4.1 on 2022-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_orders_order_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('category', models.TextField(max_length=40)),
                ('description', models.TextField(default='its juicy', max_length=100)),
                ('pimage', models.ImageField(default='', upload_to='restaurant/images')),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
