# Generated by Django 4.0.5 on 2022-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_specialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='profitPerUnit',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='totalOrders',
            field=models.IntegerField(default=0),
        ),
    ]
