# Generated by Django 4.0.5 on 2022-08-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_fooditem_profitperunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='torders',
        ),
    ]
