# Generated by Django 4.1.5 on 2023-01-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_remove_category_torders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
