# Generated by Django 4.1.5 on 2023-02-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_fooditem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_firstname',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_lastname',
        ),
    ]
