# Generated by Django 4.1.5 on 2023-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_orders_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.TextField(default='', max_length=20),
        ),
    ]
